apiVersion: v1
items:
- kind: Service
  apiVersion: v1
  metadata:
    name: ssl-proxy-service
    labels:
      role: ssl-proxy
  spec:
    ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
    selector:
      role: ssl-proxy
    type: LoadBalancer
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""